cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('products.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import index, show

app_name = 'product'

urlpatterns = [
    path('', index, name='home'),
    path('<slug:category_slug>/', index, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', show, name='product_show'),
]

templates/includes/breadcrumbs.html
<div class="breadcrumbs">        
  <div class="breadcrumbs__container" data-link="{on 'click' 'li' updateAnalytic}" data-jsv="#1552^/1552^">            
  <ul class="breadcrumbs__list" itemscope="" itemtype="https://schema.org/BreadcrumbList" data-jsv-df="">
  <li class="breadcrumbs__item" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">                   
    <a class="breadcrumbs__link" href="/" itemprop="item">                        
      <span itemprop="name">Главная</span>                 
    </a>                    
  <meta itemprop="position" content="1">                </li>
  <li data-jsv="#1550^#1242_#1243_" class="breadcrumbs__item" itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem">                       
  <script type="jsv#1244_"></script>                            
  <span itemprop="name">Мужчинам</span>                       
  <script type="jsv/1244_"></script>                        <meta itemprop="position" content="2">                    </li></ul>       
  </div>    
</div>

templates/includes/footer.html
<div id="footer">
    <div class="container">
        
        <div class="row">
            <div class="col-12">

                <!-- Contact -->
                    <section class="contact">
                        <header>
                            <h4> Тестовый проект интернет-магазина с недофронтом</h4>
                        </header>
                        <p>Осталось очень много до делать, дедлайн уже ...</p>
                    <p> Сымыаннан ссылка халлартаатым, если чо кереерун киирэн</p>
                        <ul class="icons">
                            <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
                            <li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
                            <li><a href="#" class="icon brands fa-linkedin-in"><span class="label">Linkedin</span></a></li>
                        </ul>
                    </section>

                <!-- Copyright -->
                    <div class="copyright">
                        <ul class="menu">
                            <li>&copy; Недопроект</li><li>Developer: Mark Sybakhov</li>
                        </ul>
                    </div>

            </div>

        </div>
    </div>
</div>

templates/includes/header.html
{% load static %}

<div id="header">
  <!-- Nav -->
    <nav id="nav">
      <ul>
          <li><a href="{% url 'product:home' %}">
            Главная страница
            </a>
          </li>
        <li>
         
            <a href="{% url "product:home" %}">Товары</a>
        
          <ul>
            
            {% for c in categories %}
            <li >
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
          {% endfor %}
          </ul>
        </li>
        <li><a href="#facebook">Контакты</a></li>
        <li>
        
          <div class="cart">
         
            {% with total_items=cart|length %}
              {% if total_items > 0 %}
              <a href="{% url "cart:cart_detail" %}">
              Количество {{ total_items }},
              Итого ${{ cart.get_total_price }}
              </a>
            {% elif not order %}
              Пустая корзина 
            {% endif %}
            {% endwith %}   
         </div>
        
        </li>
      
        <li class="button"><a href="">Вход </a> </li>
       <li class="button"> <a href="">Регистрация</a></li>
      </ul>
    
    </nav>
  

</div>