cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('products.urls', namespace='main')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import index, show

app_name = 'product'

urlpatterns = [
    path('', index, name='home'),
    path('<slug:category_slug>/', index, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', show, name='product_show'),
]

products/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name= 'Название категории')
    slug = models.SlugField(max_length=200, unique=True, verbose_name="Тег")
    description = models.TextField(blank = True,
                                   verbose_name='Описание категории')

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('product:product_list_by_category',
                       args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200, verbose_name= 'Тег')
    image = models.FileField(upload_to='products/%Y/%m/%d', blank=True, verbose_name= 'Картинки')
    description = models.TextField(blank=True, verbose_name='Описание')
    new_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Новая цена")
    old_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Старая цена")
    is_available = models.BooleanField(default=True, verbose_name="В наличии")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="Дата добаления")
    updated = models.DateTimeField(auto_now=True)
    #count = models.IntegerField(verbose_name="Количество")
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-pub_date']),
            ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product:product_show',
                    args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                choices=PRODUCT_QUANTITY_CHOICES,
                coerce=int, label= "Кол-во", widget=forms.TextInput)
    
    override = forms.BooleanField(required=False,
                                  initial=False,
                        widget=forms.HiddenInput)

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def index(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(is_available=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    
    return render(request,
            'product/index.html',
            {'category': category,
             'categories': categories,
             'products': products})

def show(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                is_available=True)
    
    cart_product_form = CartAddProductForm()
    return render(request,
                    'product/show.html',
                     {'product': product, 
                     'cart_product_form': cart_product_form})

templates/product/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %} Товары {% endif %}
{% endblock %}

{% block content %}

<div class="wrapper style2">

    <article id="main" class="container special">
        <a href="#" class="image featured"><img src="images/pic06.jpg" alt="" /></a>
        <header>
            <h2><a href="#"> Основнй header maina</a></h2>
            <p>
               Типа текст p
            </p>
        </header>
        <div id="sidebar">
            <h3>Категории</h3>
            <ul>
                <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "product:home" %}">Все категории</a>
                </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"
                        {% endif %}>
                        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
         </div>
        
        <p>
            Основнй панель товаров 
        </p>
        <div class="container">
            <h3>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h3>
            {% for product in products %}
                <div class="item">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                    </a>
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    <br>
                    ${{ product.new_price }}
                </div>
            {% endfor %}
         </div>
        
    </article>

</div>



{% endblock %}

templates/product/show.html
{% extends "base.html" %}
{% load static %}
{% block title %}
 {{ product.name }}
{% endblock %}
{% block content %}
 <div class="products">
 <img src="{% if product.image %}{{ product.image.url }}{% else %}
 {% static "img/no_image.png" %}{% endif %}">
 <h2>
    <a href="{{ product.category.get_absolute_url }}">
    {{ product.category }}
    </a>
</h2>
 <h2>{{ product.name }}</h2>
    
 <p class="price">${{ product.new_price }}</p>
    
 {{ product.description|linebreaks }}
 <form action="/cart/add/1/" method="post">

    
<label for="id_quantity">Кол-во:</label>

  
    <select name="quantity" id="id_quantity">
        <option value="1">1</option>

        <option value="2">2</option>

        <option value="3">3</option>

        <option value="4">4</option>

        <option value="5">5</option>

        <option value="6">6</option>

        <option value="7">7</option>

        <option value="8">8</option>

        <option value="9">9</option>

        <option value="10">10</option>

        <option value="11">11</option>

        <option value="12">12</option>

        <option value="13">13</option>

        <option value="14">14</option>

        <option value="15">15</option>

        <option value="16">16</option>

        <option value="17">17</option>

        <option value="18">18</option>

        <option value="19">19</option>

        <option value="20">20</option>

    </select>
  
  
    <input type="hidden" name="override" value="False" id="id_override">
  
   

    <input type="hidden" name="csrfmiddlewaretoken" value="zFwk7Z9smdvwkfwoFUr4ebYq2aTwSRbchdcENybCnxhp41pCIMcw1RrObkPmSjdr">
    <input type="submit" value="Добавить в корзину">
    {% csrf_token %}
</form>
 </div>
{% endblock %}